# Generated by Django 4.2.7 on 2024-03-03 14:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinywiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location='C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki'), upload_to='images/original'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_preview',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location='C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki'), upload_to='images/preview'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_sidebar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location='C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki'), upload_to='images/sidebar'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_wiki',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location='C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki'), upload_to='images/wiki'),
        ),
    ]
