# Generated by Django 4.2.7 on 2024-01-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinywiki', '0002_wikiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiimage',
            name='image_sidebar',
            field=models.ImageField(null=True, upload_to='images/wiki/sidebar'),
        ),
    ]
