# Generated by Django 4.2.7 on 2024-02-09 10:28

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_tinywiki', '0008_alter_wikiimage_image_alter_wikiimage_image_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiimage',
            name='alt',
            field=models.CharField(default='Alternative Text', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location=pathlib.PureWindowsPath('C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki')), upload_to='images/original'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_preview',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location=pathlib.PureWindowsPath('C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki')), upload_to='images/preview'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_sidebar',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location=pathlib.PureWindowsPath('C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki')), upload_to='images/sidebar'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='image_wiki',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/wiki/', location=pathlib.PureWindowsPath('C:/msys64/home/c9mos/projekte/django/django-tinywiki/media/wiki')), upload_to='images/wiki'),
        ),
        migrations.AlterField(
            model_name='wikiimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tinywiki_image_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wikiimage',
            index=models.Index(fields=['uploaded_by'], name='tinywiki_wikiimage_upby_index'),
        ),
        migrations.AddIndex(
            model_name='wikiimage',
            index=models.Index(fields=['uploaded_on'], name='tinywiki_wikiimage_upon_index'),
        ),
        migrations.AddIndex(
            model_name='wikiimage',
            index=models.Index(fields=['wiki_page'], name='tinywiki_wikiimage_page_index'),
        ),
        migrations.AddIndex(
            model_name='wikiimage',
            index=models.Index(fields=['builtin_id'], name='tinywiki_wikiimage_bid_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['slug'], name='tinywiki_wp_slug_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['language'], name='tinywiki_wp_lang_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['user'], name='tinywiki_wp_user_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['created_by'], name='tinywiki_wp_cby_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['created_on'], name='tinywiki_wp_con_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['edited_by'], name='tinywiki_wp_eby_index'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['edited_on'], name='tinywiki_wp_eon_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['slug'], name='tinywiki_wpb_slug_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['user'], name='tinywiki_wpb_user_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['edited_by'], name='tinywiki_wpb_eby_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['edited_on'], name='tinywiki_wpb_eon_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['created_by'], name='tinywiki_wpb_cby_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['created_on'], name='tinywiki_wpb_con_index'),
        ),
        migrations.AddIndex(
            model_name='wikipagebackup',
            index=models.Index(fields=['language'], name='tinywiki_wpb_language_index'),
        ),
    ]
