# Generated by Django 4.2.7 on 2024-02-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinywiki', '0010_wikipage_contentfile_md5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipage',
            options={'permissions': [('tinywiki-create-page', 'User can create pages'), ('tinywiki-delete-page', 'User can delete paegs'), ('tinywiki-edit-page', 'User can edit all pages'), ('tinywiki-edit-user-page', 'User can edit the pages he owns')]},
        ),
    ]
